### ISSUE TITLE
请问您这个项目该如何使用？

### ISSUE THREAD

**Issue by jxyddtc** [20100507/emotional_analysis#3]
非常抱歉打扰您，我是一个Java小白，希望得到您的指导

**Comment by 20100507** [comment]
需要 搭建hadoop平台，spark平台，flume平台，logstash平台，azkaban调度器平台，elasticSearch平台mysql数据库，maven环境。数据库脚本我没有上传。Spark，hadoop等搭建方法我后期有时间都写出来。如果你急需我等我毕业后给你。

**Comment by RalapQ** [comment]
您好，你的项目还有其他的没？能不能教下我。具体的开发步骤能发下吗？

**Comment by RalapQ** [comment]
您好，能留个联系方式交流下这个吗？qq：1332269597。

**Comment by RalapQ** [comment]
您好，能留个联系方式交流下这个吗？我的qq：1332268597。

**Comment by 20100507** [comment]
@RalapQ  您好我给您找一找吧，项目可能还在配置文件也可能还在
