### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by 133973** [20100507/emotional_analysis#36]
![image](https://user-images.githubusercontent.com/101243841/230867407-53ded62d-aac1-4f3f-826b-1d76d9b42208.png)
大佬你好，我已经修改了百度地图的API，请问我该怎么才能显示出分布地图？

**Comment by 20100507** [comment]
看看有没有返回数据；这些数据基本上都是我之前爬虫采集；然后使用spark进行统计分析的；
